In [2]:
# Import pandas libary abbreviated as pd
import pandas as pd
# Stop pandas from abbreviating tables to fit in the notebook
pd.options.display.max_columns = 1000
pd.options.display.max_rows = 1000
# Display graphs in the notebook
%matplotlib inline

In [6]:
# read in our csv file, and automatically change missing values into NaN
pay = pd.read_csv('hospital-admissions-rates-borough.csv', na_values = ['.',' '])
# Use the head function to see the first few rows
pay.head(100).set_index('Area').sort_values('Area')

,Resident Population (2014) - Denominator,Number of Admission Continuous Inpatient Spells - Numerator,Expected value,"Indirectly age and sex standardised rate per 100,000",Lower limit of 95% confidence interval,Upper limit of 95% confidence interval,Lower limit of 99.8% confidence interval,Upper limit of 99.8% confidence interval
Area,,,,,,,,
Barking and Dagenham,198294.0,16019.0,16392.11,8964.89,8826.59,9104.81,8747.60,9185.93
Barnet,374915.0,24493.0,33178.08,6772.28,6687.73,6857.64,6639.35,6907.07
Bexley,239865.0,19131.0,22255.70,7885.71,7774.36,7998.26,7710.70,8063.48
Brent,320762.0,25077.0,26548.40,8665.26,8558.33,8773.18,8497.15,8835.69
Bromley,321278.0,27018.0,30443.97,8141.35,8044.55,8239.01,7989.15,8295.57
Camden,234846.0,15680.0,19392.58,7417.45,7301.80,7534.48,7235.75,7602.33
City of London,8072.0,356.0,725.49,4501.58,4046.03,4994.37,3800.06,5288.82
Croydon,376040.0,28091.0,32459.49,7939.07,7846.50,8032.47,7793.50,8086.54
Ealing,342118.0,31166.0,28685.62,9966.92,9856.57,10078.21,9793.37,10142.62
East Midlands,4637413.0,448566.0,437275.96,9410.55,9383.03,9438.13,9367.19,9454.05
East of England,6018383.0,552982.0,577336.96,8786.70,8763.56,8809.89,8750.23,8823.28
Enfield,324574.0,25954.0,27943.05,8520.69,8417.34,8625.00,8358.19,8685.40
England,54316618.0,5131589.0,5068559.96,9287.77,9279.74,9295.81,9275.11,9300.45
Greenwich,268678.0,18336.0,22046.55,7629.72,7519.67,7740.96,7456.78,7805.44
Hackney,263150.0,6971.0,19980.65,3200.59,3125.89,3276.62,3083.43,3320.83
Hammersmith and Fulham,178365.0,14789.0,14302.70,9485.60,9333.33,9639.74,9246.39,9729.12
Haringey,267541.0,21200.0,20986.03,9267.23,9142.90,9392.83,9071.79,9465.60
Harrow,246011.0,19305.0,22065.81,8025.91,7913.09,8139.94,7848.59,8206.02
Havering,245974.0,20965.0,23772.08,8090.44,7981.29,8200.71,7918.87,8264.60
Hillingdon,292690.0,27385.0,25399.15,9890.95,9774.14,10008.80,9707.28,10077.04
Hounslow,265568.0,23614.0,21982.27,9854.65,9729.36,9981.16,9657.67,10054.44
Inner London,3395655.0,204233.0,267297.08,7009.32,6978.95,7039.79,6961.49,7057.38
Islington,221030.0,17008.0,17226.25,9057.47,8921.85,9194.63,8844.37,9274.15
Kensington and Chelsea,156190.0,10618.0,13449.81,7242.21,7105.10,7381.30,7026.96,7462.03
Kingston upon Thames,169958.0,10396.0,14796.67,6445.35,6322.04,6570.46,6251.77,6643.09
Lambeth,318216.0,22588.0,24386.61,8497.10,8386.64,8608.65,8323.46,8673.26
Lewisham,291933.0,23459.0,23480.97,9165.11,9048.20,9283.16,8981.31,9351.53
London,8538689.0,610831.0,714817.80,7839.17,7819.52,7858.85,7808.21,7870.21
Merton,203515.0,12686.0,17372.90,6698.79,6582.72,6816.40,6516.51,6884.63
Newham,324322.0,9266.0,24558.21,3461.31,3391.18,3532.51,3351.25,3573.87
North East,2618710.0,311168.0,247795.98,11519.80,11479.36,11560.35,11456.09,11583.76
North West,7132991.0,846830.0,666186.75,11661.23,11636.41,11686.10,11622.11,11700.45
Outer London,5143034.0,406598.0,447520.72,8334.82,8309.22,8360.48,8294.49,8375.29
Redbridge,293055.0,23201.0,25030.55,8503.17,8394.10,8613.30,8331.70,8677.09
Richmond upon Thames,193585.0,12866.0,17319.52,6814.78,6697.53,6933.58,6630.63,7002.49
South East,8873818.0,715584.0,846961.49,7750.71,7732.76,7768.69,7722.42,7779.06
South West,5423303.0,505560.0,541106.58,8571.05,8547.44,8594.71,8533.85,8608.37
Southwark,302538.0,23285.0,23469.12,9101.73,8985.19,9219.40,8918.52,9287.56
Sutton,198134.0,17986.0,17838.30,9249.65,9114.96,9385.84,9037.98,9464.77
Tower Hamlets,284015.0,6992.0,20976.98,3057.76,2986.50,3130.28,2946.00,3172.45
Waltham Forest,268020.0,22909.0,21990.51,9556.86,9433.50,9681.43,9362.93,9753.59
Wandsworth,312145.0,16504.0,25035.37,6047.55,5955.63,6140.53,5903.12,6194.43
West Midlands,5713284.0,590475.0,536540.06,10095.87,10070.13,10121.65,10055.32,10136.53
Westminster,233292.0,15517.0,19326.31,7365.51,7250.07,7482.33,7184.14,7550.07
Yorkshire and the Humber,5360027.0,549593.0,500538.39,10072.75,10046.14,10099.42,10030.82,10114.81
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN